export default {
    REPOSITORY_GET: 'REPOSITORY_GET',
    CREATE_MATRIX: 'CREATE_MATRIX',
    GET_MATRIX: 'GET_MATRIX',
    ADD_TASK: 'ADD_TASK',
    CLEAR_TASKS: 'CLEAR_TASKS',
    MATRIX_REPOSITORY: 'MATRIX_REPOSITORY',
};
